version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: barter
      POSTGRES_PASSWORD: barter123
      POSTGRES_DB: barter_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
      - static:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pg_data:
  static: